name: chronograf
version: 1.6.0
description: Chart for Chronograf
keywords:
- chronograf
- visualizaion
- timeseries
home: https://www.influxdata.com/time-series-platform/chronograf/
maintainers:
- name: 
  email: 
engine: gotpl
