apiVersion: batch/v1
kind: Job
metadata:
  name: "{{.Release.Name}}"
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "-5"
spec:
  template:
    metadata:
      name: "{{.Release.Name}}"
      labels:
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    spec:
      restartPolicy: Never
      containers:
      - name: post-install-job
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        env:
          - name: KAPACITOR_URL
            value: "http://{{ template "fullname" . }}.{{ .Release.Namespace }}:9092"
        command:
          - "/usr/bin/kapacitor"
          - "define"
          - "prometheus-influxdb-out"
          - "-type"
          - "stream"
          - "-tick"
          - "/var/lib/kapacitor/influxdb_out.tick"
          - "-dbrp"
          - "prometheus_raw.autogen"
          - "&&"
          - "/usr/bin/kapacitor"
          - "enable"
          - "prometheus-influxdb-out"
        volumeMounts:
        - name: tick-scripts
          mountPath: /var/lib/kapacitor/
      volumes:
      - name: tick-scripts
        configMap:
          name: {{ template "fullname" . }}-tasks
        